### ISSUE TITLE
Add homebrew formula for unified version

### ISSUE THREAD

**Issue by magicDGS** [robmaz/distmap#8]
Once the unified version is out, we should add a DistMap formula to https://github.com/vetmeduni/homebrew-popgen

**Comment by robmaz** [comment]
This was of course my intention all the time. I would, however, before that also want to clean up the folder structure a bit to become more standard. The mappers would maybe go into /usr/libexec/ {linux,macos} where we would probably also look for them if they were not distributed with distmap and are not in the path, so that also prepares making them external. The jars and perl modules into /usr/lib/distmap/{java,perl}, respectively? The distmap script into /usr/bin

**Comment by robmaz** [comment]
We have a working distmap formula now.
